### ISSUE TITLE
Frage: Anpassung Geonode Metadatenformular oder Integration des neuen Upload-Tools

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#12]
Ich bin mir nicht sicher, ob wir das Geonode Formular zur Metadateneingabe anpassen oder wie geplant unser Upload-Tool erweitern (siehe [Whimsical ](https://whimsical.com/upload-tool-DjbAr2sswApXXWM3oVoo81)).

**Comment by mwallschlaeger** [comment]
hier würde ich für den ORD release auf den MEtadaten Editor von GeoNode vertrauen und im Anschluss nach der testphase mit den ORD daten eine entscheidung treffen wollen

**Comment by mwallschlaeger** [comment]
is geklaert upload tool wird bleiben
