### ISSUE TITLE
Datasets with embedded coordinates or without

### ISSUE THREAD

**Issue by krmeierzalf** [zalf-rdm/geonode#123]
UseCase 1: geodata is contained in dataset. Right now we extract geodata and save seperately in DB. This is redundant. 
What makes sense? Discard the separate geodata or keep both? 

UseCase 2: datatables do not contain geodata -> geodata was created from scratch by data stewards. We have to keep this because we cannot add geodata to published datasets.

**Comment by mwallschlaeger** [comment]
in my opinion remove unnecessary seperation of files is a plus. GeoNode is able to identify geodata from csv by column names. So a when uploading csv files containing x,y or long, lat geonode would handle this datasets as geodata. Therefore I would suggest to not copy additional geodata for dataset.

@specka what do you think?

**Comment by specka** [comment]
Sorry, but I dont understand, where do you want to go or the real nature of the issue. You need to explain it to me ...
