### ISSUE TITLE
Download eines Datensatzes in verschiedenen Formaten anbieten

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#13]
Aktuell ist es so, dass im BonaRes Repositorium die Daten in verschiedenen Formaten heruntergeladen werden können. Es wäre schön, wenn das auch im neuen Repositorium gehen würde. Allerdings sollten nur die Formate möglich sein, die auch Sinn machen. Das ist aktuell im BonaRes Repositorium schlecht umgesetzt.

**Comment by mwallschlaeger** [comment]
geonode provides this feature out of the box
