### ISSUE TITLE
Bug: geonodectl command "dataset list" throws 500 Server Error

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#132]
## Bug Description

After installating geonodectl on my desktop via PyCharm and setting the environmental variables, I tried to executed the command
`geonodectl dataset list`

## Reproduction Steps

- execute geonodectl with the following command
`geonodectl dataset list`

(GEONODE_API_URL=https://repository.zalf.de/api/v2/)

##  Behavior

Error message in the command line: "500 Server Error: Internal Server Error for url: https://repository.zalf.de/api/v2/datasets/?page_size=80&page=1"

**Comment by mwallschlaeger** [comment]
this was an issue with one dataset inside the geonode which called a strange behavior

**Comment by specka** [comment]
Sucessfully tested today. Command `geonodectl ds list` and `geonodectl dataset list` worked as expected.

![Image](https://github.com/zalf-rdm/geonode/assets/3841997/43159a64-c142-4f19-9eef-9534de7bf84d)
