### ISSUE TITLE
Task:  Discussion on future of Related projects 

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#133]
## Task Description
Do we continue to use the previous BonaRes Projects as metadata entry for related projects, or do we overcome these. How to implement this field in general? BonaRes mapping linked this to hierarchyLevelName in inspire but when i read description on hierarchyLevelName inside the inspire standard this seems odd to me.

Screenshot from inspire standard:
![image](https://github.com/zalf-rdm/geonode/assets/17499481/80cf95fe-6287-48b8-adb9-8cfceb2f89ed)

**Comment by specka** [comment]
Konsens or idea from 02.07.2024:
- we need a separate system (FDM Project Database), in which we can manage all project information required for the publication of ZALF and external datasets
- this database will be filled with information and  synchronized on the one hand by the ZALF Projektdatenbank (information from the PAP system)
- this database allows also the "manual" addition of external projects
- it also enables to integrate further project database from other institutions (e.g. from Kassel university)
- this system will be also used in the Upload Tool to faciliate project selection in the dataset submission

**Comment by mwallschlaeger** [comment]
in addition to that: we agreed on not using  the inspire field `HierachyLevelName` anymore. Our interpretation of the field does not follow the official inspire interpretation.

**Comment by mwallschlaeger** [comment]
closed with: https://github.com/orgs/zalf-rdm/discussions/5
