### ISSUE TITLE
When resources are available

### ISSUE THREAD

**Issue by ridoo** [zalf-rdm/geonode#137]
* https://github.com/GeoNodeUserGroup-DE/importer-datapackage/issues/3
* https://github.com/GeoNodeUserGroup-DE/geonode-dev-datapackage/issues/21
* https://github.com/GeoNodeUserGroup-DE/geonode-dev-datapackage/issues/23

**Comment by mwallschlaeger** [comment]
I imported the issues back into the board. We will decided based on all issues in the board
