### ISSUE TITLE
Task: clarify data protection issues with project list in the Upload Tool

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#138]
Niko consults Florian Melzer, to get his consent, that this information is not sensitive and can be presented for all "users" in the Upload Tool

**Comment by svoboda-zalf** [comment]
Process of clarification started; Document to be handed over to Florian written and under review by Kristin.

**Comment by svoboda-zalf** [comment]
Document improved by Kristin and handed over to Florian

**Comment by svoboda-zalf** [comment]
Ping an Florian...

**Comment by specka** [comment]
@svoboda-zalf Wie ist hier der Status?

**Comment by svoboda-zalf** [comment]
fi
[Stellungnahme BonaRes-Projektdaten in Metadaten übernehmen.pdf](https://github.com/user-attachments/files/17028374/Stellungnahme.BonaRes-Projektdaten.in.Metadaten.ubernehmen.pdf)
nalized. We are allowed to utilize the ZALF Project data base.
