### ISSUE TITLE
Feature: in preparation of unifing the people.organization field with the base.FundingReference

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#142]
## Task Description
In https://github.com/orgs/zalf-rdm/discussions/7, we discussed that the people.organization field should not be a free text field anymore. It must be backed with a list of organizations managed by data stewards through the admin interface. This allows us to reuse already gathered organization information, and reduce the amount of duplicates in the system. In TF we agreed that this list partially shares the same institutions as the base.FundingReference list. In other words an institution can be a funding reference or a organization people work for. Therefore we're going to have those institutions in a single list.

To prepare the unification of the people.organization and the  base.FundingReference, the funding reference list may be renamed and extend by required information in the first place. New required fields are **(Please doublecheck)**:
- address information
- contact information
- RoR (funder_identifier)
- name of the institution (funder_name)
- abbreviation (funder_identifier_type)

**Further this list requires an Admin interface to add, delete or edit entries. And an API endpoint to get organizations and add or delete organizations with admin or staff rights.**

**Comment by krmeierzalf** [comment]
Also important here: https://docs.google.com/spreadsheets/d/13L0YwcsIv4psKz4XLpqHpnsTv9XtRnZpMeZ1SwMxmJU/edit?pli=1&gid=396474177#gid=396474177
Should we continue using this document?

**Comment by mwallschlaeger** [comment]
@krmeierzalf I think i wouldn't keep the data in separate excel list. As soon as we created the organizations from ORD combined with the one from the funding agencies list, we can continue work with them in geonode and take care of them via the admin table. At this point we are also deleting the list in the docs to reduce redundancy
