### ISSUE TITLE
Feature: make people organization a list choice

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#143]
### depends on:
-  https://github.com/zalf-rdm/geonode/issues/142

## Feature Description
current field people.organization is a free text  field. this must be changed to be a choice select from the organizations list created in #142 . As backend work is already done in #142 this issue is focused on the representation in the people.profile view and the corresponding edit profile. 

We must evaluate in how this could interfere with getting users from keycloak, also we may can automatically set organization if users are login in with zalf mail addr.?

**Comment by silvadealmeida** [comment]
same list as funder names

**Comment by specka** [comment]
@silvadealmeida How can I test this one here? I see the list of organizations used in "funding references". How can I check the "people" part?
