### ISSUE TITLE
Task: Prepare test datasets for the GeoNode Retreat

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#181]
## Task Description

We need different test datasets to test the Upload Tool and GeoNode. 
- geodata (x,y coordinates)
- with a shapefile 
- Non-Geo dataset
- Rasterdaten

## Additional Information

Any additional information or context that may be helpful in completing the task.

**Comment by specka** [comment]
Questions formulated by Kevin und Kristin in a TF GeoNode Meeting: https://github.com/orgs/zalf-rdm/discussions/9#discussion-7100271

**Comment by mwallschlaeger** [comment]
retreat is done
