### ISSUE TITLE
Question: can we access ZALF GeoNode and the Upload Tool (ENTW) without VPN access

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#182]
## Task Description

Question with respect to the GeoNode Retreat: can we access our services like GeoNode and Upload Tool without VPN?

**Comment by silvadealmeida** [comment]
@specka The upload tool is not available in the test environment yet, at the moment it just runs locally. I have a meeting with Henning tomorrow (19.09.24)  and I will try to organize it to be available in the test environment.

**Comment by specka** [comment]
Wenn es nicht möglich ist, auf der Testumgebung auszurollen, dann führen wir das Upload-Tool über dein Notebook vor und testen es entsprechend. Das ist kein Problem, ich möchte nur gern vorher wissen, was möglich ist, und was nicht.

**Comment by mwallschlaeger** [comment]
We can access the GeoNode and have VPN at retreat
