### ISSUE TITLE
Check 52N implementation and integration into GeoNode before Retreat

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#183]
- check status of current 52N implementation
- analyse what steps need to be done in order to get this version integrated into our GeoNode instance
- if necessary, contact 52N and use budget of th eupload tool implementation for some final steps --> agreed by Xenia

**Comment by mwallschlaeger** [comment]
@specka i checked and merged 52N implementation with ZALF Geonode and geonode 4.3.1 and make it accessible on repository.zalf.de
