### ISSUE TITLE
Anzeige von Datensatz Views und Downloads

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#28]
**Is your feature request related to a problem? Please describe.**
Detailseite von Datensätzen.

**Describe the solution you'd like**
Es wäre schön, wenn bei jedem Datensatz im Hintergrund eine Statistik mitläuft, wie oft der Datensatz angeschaut wurde und auch heruntergeladen wurde, ähnlich wie bei Zenodo:
![image](https://user-images.githubusercontent.com/3841997/223729879-04b91dc2-2cf1-4af4-b054-9ee2f7556507.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by mwallschlaeger** [comment]
improved description in #49
