### ISSUE TITLE
Non Spatial Data contrib module

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#30]
Install an test non spatial data contrib module from 52n

**Comment by mwallschlaeger** [comment]
this is now part of the 52N workpackage: see full description here: https://docs.google.com/document/d/1o0FnIbRTXNms3fVepsVAL3WODeBmZkBBcjsbGd8SdE8/edit?usp=sharing

**Comment by mwallschlaeger** [comment]
this issue must be seperated into a milestone including multiple issues.

**Comment by specka** [comment]
siehe auch #81

**Comment by ridoo** [comment]
duplicate of #81
