### ISSUE TITLE
Bug: Some Metadata values cannot be configured via advanced metadata editor

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#47]
When editing metadata in the advanced metadata editor the following metadata fields cannot be set due to problems with the forms:
-  Use_constrains 
- Restrictions
-  Related Identifier
-  Funder names
-  Related project (hierarchyLevelName in the INSPIRE metadata scheme)

**Comment by silvadealmeida** [comment]
as 
- Use_constrains
- Restrictions

are part of the latest discussion in the TF. We are moving them to a separate issue. I gonna link this below

**Comment by mwallschlaeger** [comment]
@silvadealmeida please also skip Related project for now as well. concentrate first on `Related Identifier` and `Funders`

here is an example of the Funder editor field in the current metadata editor:
![Image](https://github.com/zalf-rdm/geonode/assets/17499481/2d166e36-2e33-4f7d-9be9-e2d38df4f085)

and here the example of thee related identifier configuration from the current smartfinder.SDI:
![Image](https://github.com/zalf-rdm/geonode/assets/17499481/8fc3c473-b7ca-4513-b3a4-6d1dccd6de3c)

**Comment by mwallschlaeger** [comment]
created individual issues
