### ISSUE TITLE
Task: Configure Advanced Workflow 

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#52]
## Task Description

Geonode Supports an so called [advanced workflow](https://docs.geonode.org/en/master/admin/admin_panel/index.html#how-to-enable-the-advanced-workflow) to allow publication process of datasets by group admins. This must be configured in the first place. The link.

## Additional Information

Any additional information or context that may be helpful in completing the task.

**Comment by specka** [comment]
Is this something we need to discuss with our data stewards because it affects the datapublication workflow?

**Comment by mwallschlaeger** [comment]
i would say so
