### ISSUE TITLE
User story: Enable download of data without provision of personal information

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#72]
## Feature Description

If a scientist submits a paper to a journal, often reviewers also check availability of related research data that was published as part of the paper. As this is a "double-blind-process", reviewers need to download data without providing the personal information such as email address.

Nevertheless, I (XS) would also prefer, that a direct data download could be enabled with Geonode without this step of sending around an email with an download link. I hope, that this comes naturally with Geonode. But if not, we need to implement it.

## Proposed Solution

Download of Geo and Non-Geo-Data without login or provision of email address.

## Additional Information

Any additional information or context that may be helpful in implementing the feature.

**Comment by mwallschlaeger** [comment]
if a dataset is published in GeoNode it's by default downloadable for everybody.
