### ISSUE TITLE
Task: need to change available categories in the metadata editor

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#75]
Current available categories in GeoNode does not fit to our Categorization of datasets. We need to change them. is this possible?

![Image](https://github.com/zalf-rdm/geonode/assets/3841997/275839d9-42ab-400a-921b-6e71e5a1a6ae)

**Comment by specka** [comment]
Decision from our meeting on 02.07.2024: in GeoNode, the original INSPIRE categories won't be touched. They just stay the same as the INSPIRE standard requires. 

BUT: we have to reduce the "categories" in the Upload Tool. @specka: create a new issue for the Upload-Tool, to either integrate categories in the Upload Tool or reduce the number of available choices for categories.

**Comment by mwallschlaeger** [comment]
closed with: https://github.com/orgs/zalf-rdm/discussions/5
