### ISSUE TITLE
setup mail address for the test instance

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#79]

**Comment by specka** [comment]
There was already an IT issue: it needs to be activated again. So far Mr. Machens had no objections ...

**Comment by mwallschlaeger** [comment]
neues ticket gezogen: Ticket-Nr. 2024060301000286. für repository@zalf.de und repository-e@zalf.de

**Comment by specka** [comment]
Waiting for IT to solve the ZALF-IT ticket. Therefore moved to blocked ...

**Comment by mwallschlaeger** [comment]
use the repository email addr. as admin account mail addr. in geonode

**Comment by mwallschlaeger** [comment]
I asked thomas for a mail addr. for repository.dataservice.zalf.de

**Comment by mwallschlaeger** [comment]
got access to send mail from draven hosts
