### ISSUE TITLE
Question: Should we upgrade to GeoNode 4.3?

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#83]
## Task Description

New GeoNode release 4.3 will be available soon; we have to check with 52N, if we want to go for the next GeoNode release.
- What are the benefits of the new version?
- How big would the effort be to upgrade our system to this new version?
We need to have an answer here soon.

**Comment by specka** [comment]
This question will be important with respect to the 52N implementation.

**Comment by mwallschlaeger** [comment]
After 52N implemented nonspatial datasets "contrib module" we decided on using 4.3.0
