### ISSUE TITLE
Task: analyse dataset status of GeoNode and develop a concept of how we use this in our data publication workflow 

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#86]
## Task Description

We need to find out, what different status and workflows GeoNode provides and how the will integrate in our data publication workflow.

## Additional Information

Any additional information or context that may be helpful in completing the task.

**Comment by specka** [comment]
EPIC: #84

**Comment by mwallschlaeger** [comment]
FYI geonode generally only supports only two status published , and unpublished. Published mean public to everyone und and unpublished means private and only visiable to user and group.
