### ISSUE TITLE
Task: how to integrate organizations into geonode

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#90]
current geonode only supports organisations as a free text field. to improve reusablility of organizations integrating https://ror.org/ could be an option for users and funding agencies. 

@specka what is your oppinion on this?

**Comment by specka** [comment]
This is definitely a good idea, and we already planned this for the con terra repositorium. But it was never implemented. So please put this as a feature to our Geonode development so we can schedule this into our sprint planning. But to be honest, it's nothing, that we will implement.

**Comment by mwallschlaeger** [comment]
ref: https://github.com/orgs/zalf-rdm/discussions/7

We agreed on reusing the funding agencies list as the place to also store organizations for people. This list must include a number of additional fields so that all required information can be set to the ISO:19115 output xml, including full address and maybe more. Unregarding the use of the organization as funding agency or as peoples organization at both points data stewards are able to add new organizations to the list using the admin interface or by adding them through the API from the upload tool. A person can only be part of one organization at the time.
