### ISSUE TITLE
Task: use GeoNode regions to support NUTS

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#91]
current geonode regions support continents and countries. but for our usecase i might be a good idea to increase accuracy of this field by add more details. an option would be the nuts identifier (https://ec.europa.eu/eurostat/web/nuts) a european standard. 

This is also related to place keywords in bonares repo and location in ord repo. Furhter focus areas could be integrated into this field.

**Comment by KevinUrbasch** [comment]
https://gadm.org/ world wide administrative boundaries; possible that nuts regions are already part of it

**Comment by mwallschlaeger** [comment]
ref: https://github.com/orgs/zalf-rdm/discussions/7

We agreed that having regional keywords like place keywords is a nice thing to have. Within the Task Force we all agreed on the following:
- we're going to overload GeoNode regions by NUTS or GADM Regions + focus areas.
- this NUTS based place keywords are set automatically by the upload tools, background process based on the uploaded geodata or geodata set in the upload tool
- details on howto implement the place keyword infer from a bounding box must be discussed in a separate issue
