### ISSUE TITLE
How to structure data / data collections inside GeoNode (maps, datasets, documents, stories, metadata)

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#93]
GeoNode supports several object types to represent geodata, non geodata and metadata. We never decided on how a publication is structured inside our GN repository. Everybody in our working group must be familiar with the geonode object types and know our guidelines on how to handle different data formats within this structure.

**Comment by mwallschlaeger** [comment]
discussed and sovled in: https://github.com/orgs/zalf-rdm/discussions/2#discussion-6781523
