### ISSUE TITLE
Question: authors and user accounts in GeoNode

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#97]
Basic problem is that all users related in GN metadata must be users inside the geonode repos. But users come from different sources: ORD, BonaRes Repo, ZALF AD, BonaRes AD, ORCID. 

Users must be identified as themself no matter where they come from, and if we create them beforehand e.g. by ORD upload, they still need to be connected to their already uploaded datasets when uploading for the first time after zalf geonode launch. 

Further we must discuss how new users enter the system?

**Comment by specka** [comment]
Konsens from 5.6.2024 
- only local admin users can login into GeoNode
- authors are created by GN admins as local user accounts
- Based on information from upload tool, in this tool GeoNode groups can be automatically created / assigged (e.g. Uni Kassel)
- When author details has ORCID ID provided in the Upload-Tool
- We will automatically create a user profile and integrate information from they ORCID profile → Niko will check data protection issues

**Comment by gannebamm** [comment]
Maybe of interest: https://github.com/GeoNode/geonode/issues/10342

I had the same issue with GeoNodes rigid metadata contact = GeoNode User binding. Our idea was similar: Use non-login contacts to store those information. But see: https://github.com/GeoNode/geonode/issues/11511#issuecomment-2196702015
